apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv-wordpress
spec:
  storageClassName: wordpress
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
          path: /data
